Ejercicio 1 - Numpy

In [2]:
import numpy as np

# 1.- Crear un vector “x” con 10 ceros y mostrarlo.
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#  2.- Modificar el quinto elemento del vector x para que su valor sea 3.
x[4] = 3
x 

array([0., 0., 0., 0., 3., 0., 0., 0., 0., 0.])

In [4]:
# 3.- Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.
y = np.arange(1,20,1)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
# 4.- Crear un vector “z” con valores del 1 al 20, de 2 en 2.
z = np.arange(1,20,2)
z

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
#  5.- Crear una matriz w de 3x2, con valores iniciales en 0.
w = np.zeros((3,2))
w

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
# 6.- Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.
w[1,1] = 5
w

array([[0., 0.],
       [0., 5.],
       [0., 0.]])

In [8]:
# 7.- Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.
q = np.random.randint(1,10,5)
q

array([1, 3, 7, 9, 4], dtype=int32)

In [9]:
#   8.- Crear el arreglo x1 de la lista [1,2,3]

x1 = np.array([1, 2, 3])
x1

array([1, 2, 3])

In [10]:
#  9.-  Sumar 10 a cada elemento del vector
scalar = 10
result = np.add(x1, scalar)
print(result)

[11 12 13]


Ejercicio 2

In [11]:
import pandas as pd
archivo = pd.read_csv('titanic-1.csv')
df = pd.DataFrame(archivo)
df.info()
print(df.head(10))
print(df.tail(10))
print(df)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0    

In [12]:
# 3.Mostrar por pantalla los datos del pasajero con identificador 148.
print(df.loc[147])

PassengerId                                 148
Survived                                      0
Pclass                                        3
Name           Ford, Miss. Robina Maggie "Ruby"
Sex                                      female
Age                                         9.0
SibSp                                         2
Parch                                         2
Ticket                               W./C. 6608
Fare                                     34.375
Cabin                                       NaN
Embarked                                      S
Name: 147, dtype: object


In [13]:
# 4. Mostrar por pantalla las filas pares del DataFrame.
# print(df.loc[df['PassengerId' % 2 == 0]]) incorrecto
print(df.iloc[::2])

     PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
4              5         0       3   
6              7         0       1   
8              9         1       3   
..           ...       ...     ...   
882          883         0       3   
884          885         0       3   
886          887         0       2   
888          889         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ... 

In [14]:
# 5. Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.
df1 = df.loc[df['Pclass'] == 1]
df1.sort_values('Name')

PassengerId  Survived  Pclass  \
730          731         1       1   
305          306         1       1   
297          298         0       1   
498          499         0       1   
460          461         1       1   
..           ...       ...     ...   
155          156         0       1   
351          352         0       1   
55            56         1       1   
555          556         0       1   
325          326         1       1   

                                                Name     Sex    Age  SibSp  \
730                    Allen, Miss. Elisabeth Walton  female  29.00      0   
305                   Allison, Master. Hudson Trevor    male   0.92      1   
297                     Allison, Miss. Helen Loraine  female   2.00      1   
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1   
460                              Anderson, Mr. Harry    male  48.00      0   
..                                               ...     ...    ...    ...   
155                      Williams, Mr. Charles Duane    male  51.00      0   
351           Williams-Lambert, Mr. Fletcher Fellows    male    NaN      0   
55                                 Woolner, Mr. Hugh    male    NaN      0   
555                               Wright, Mr. George    male  62.00      0   
325                         Young, Miss. Marie Grice  female  36.00      0   

     Parch    Ticket      Fare    Cabin Embarked  
730      0     24160  211.3375       B5        S  
305      2    113781  151.5500  C22 C26        S  
297      2    113781  151.5500  C22 C26        S  
498      2    113781  151.5500  C22 C26        S  
460      0     19952   26.5500      E12        S  
..     ...       ...       ...      ...      ...  
155      1  PC 17597   61.3792      NaN        C  
351      0    113510   35.0000     C128        S  
55       0     19947   35.5000      C52        S  
555      0    113807   26.5500      NaN        S  
325      0  PC 17760  135.6333      C32        C  

[216 rows x 12 columns]

In [15]:
# 7. Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.

yes = df[df["Survived"] > 0]
survived = len(yes)/len(df)*100
not_survived = 100 - survived
print('Survived = ', survived)
print('Not Survived =', not_survived)


Survived =  38.38383838383838
Not Survived = 61.61616161616162


In [16]:
# 8. Eliminar del DataFrame los pasajeros con edad desconocida.
df_nan = df['Age'].dropna()
print(df_nan)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: Age, Length: 714, dtype: float64


In [17]:
# 9. Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.
